name: example
description: Example.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  mno_server:
    path: ../
  mno_shared:
    path: ../../shared
  universal_io: ^2.2.2

dev_dependencies:
  lints: ^3.0.0

dependency_overrides:
  collection: ^1.18.0
